import { ICardDetails } from 'src/types/types';
import { DUMMY_NAME } from 'src/utils/helpers';

export const EXAMPLE_CARD: ICardDetails = {
  name: 'Mark Henry',
  cardNumber: '1234234134122020',
  validThru: '12/24',
  cvv: '000',
  type: 'visa',
  frozen: false,
  cancelled: false,
  transactions: [
    {
      id: 5,
      name: 'Hamleys',
      amount: 150,
      currency: 'S$',
      desc: 'Refund on debit card',
      date: '20 May 2020',
      category: 'unknown',
      txnType: 'credit',
    },
    {
      id: 6,
      name: 'Hamleys',
      amount: 150,
      currency: 'S$',
      desc: 'Charged to debit card',
      date: '20 May 2020',
      category: 'flight',
      txnType: 'debit',
    },
    {
      id: 7,
      name: 'Hamleys',
      amount: 150,
      currency: 'S$',
      desc: 'Charged to debit card',
      date: '20 May 2020',
      category: 'entertainment',
      txnType: 'debit',
    },
    {
      id: 8,
      name: 'Hamleys',
      amount: 150,
      currency: 'S$',
      desc: 'Charged to debit card',
      date: '20 May 2020',
      category: 'unknown',
      txnType: 'debit',
    },
  ],
};

export const EXAMPLE_CARD_2: ICardDetails = {
  name: 'Sourav Das',
  cardNumber: '1234234134122023',
  validThru: '12/24',
  cvv: '010',
  type: 'visa',
  frozen: false,
  cancelled: false,
  transactions: [
    {
      id: 1,
      name: 'Hamleys',
      amount: 150,
      currency: 'S$',
      desc: 'Refund on debit card',
      date: '20 May 2020',
      category: 'unknown',
      txnType: 'credit',
    },
    {
      id: 2,
      name: 'Goa Flight',
      amount: 150,
      currency: 'S$',
      desc: 'Charged to debit card',
      date: '20 May 2020',
      category: 'flight',
      txnType: 'debit',
    },
    {
      id: 3,
      name: 'Inox Movie',
      amount: 150,
      currency: 'S$',
      desc: 'Refund on debit card',
      date: '20 May 2020',
      category: 'entertainment',
      txnType: 'credit',
    },
    {
      id: 4,
      name: 'Hamleys',
      amount: 150,
      currency: 'S$',
      desc: 'Charged to debit card',
      date: '20 May 2020',
      category: 'unknown',
      txnType: 'debit',
    },
  ],
};

export const DUMMY_DATA: ICardDetails = {
  name: DUMMY_NAME,
  cardNumber: DUMMY_NAME,
  cvv: DUMMY_NAME,
  validThru: DUMMY_NAME,
  transactions: [],
  type: 'visa',
  frozen: false,
  cancelled: false,
};
